#!/bin/bash

#
# List all users on the given cloud account

. $BASHRC_BASE/bashrc/errors.bash

function usage() {
  echo "Usage: brc-identity-listusers [-h] [-a BRC_AUTHTOKEN]"
  echo "Example:"
  echo "  # brc-identity-listusers -a 1a2b3c4d5e6f7g8h9i0j"
  echo "Example:"
  echo "  # export BRC_AUTHTOKEN=1a2b3c4d5e6f7g8h9i0j"
  echo "  # brc-identity-listusers"
}

USAGEFLAG=0
while getopts ":ha:" arg; do
  case $arg in
    a) BRC_AUTHTOKEN=$OPTARG;;
    h) usage && exit 0;;
    :) echo "ERROR: Option -$OPTARG requires an argument."
       USAGEFLAG=1;;
    *) echo "ERROR: Invalid option: -$OPTARG"
       USAGEFLAG=1;;
  esac
done #End arguments
shift $(($OPTIND - 1))

if [ -z $BRC_AUTHTOKEN ]; then
  echo "ERROR: Must define BRC_AUTHTOKEN in environment or argument"
  USAGEFLAG=1
fi

if [ $USAGEFLAG -ne 0 ]; then
  usage && exit 1
fi

DATA=$( curl --write-out \\n%{http_code} --silent --output - \
             $IDENTITY_ENDPOINT/users \
             -H "Content-Type: application/json" \
             -H "X-Auth-Token: $BRC_AUTHTOKEN" \
          2>/dev/null )
RETVAL=$?
CODE=$( echo "$DATA" | tail -n 1 )

# Check for failed API call
if [ $RETVAL -ne 0 ]; then
  errorcurlfail
elif [[ $(echo "$CODE" | grep -cE '^2..$') -eq 0 ]]; then
  errornot200 $CODE $( echo "$DATA" | head -n -1 )
fi

DATA=$( echo "$DATA" | head -n -1 | brc-json.tool )

USERIDS=$( echo "$DATA" \
             | sed -n 's/bashrc~users~username.\([0-9]*\)~.*$/\1/p' )

# Just clean up the output a bit
echo ---
for x in $USERIDS; do
  echo "$DATA" | grep "\.$x~"
  echo ---
done
