#!/bin/bash

#
# List available roles on the given cloud account

function usage() {
  echo "Usage: brc-identity-listroles [-t BRC_TENANTID] [-a BRC_AUTHTOKEN]"
  echo "Example:"
  echo "  # brc-identity-listroles -t 123456 -a 1a2b3c4d5e6f7g8h9i0j"
  echo "Example:"
  echo "  # export BRC_TENANTID=123456"
  echo "  # export BRC_AUTHTOKEN=1a2b3c4d5e6f7g8h9i0j"
  echo "  # brc-identity-listroles"
}

while getopts ":ht:a:" arg; do
  case $arg in
    t) BRC_TENANTID=$OPTARG;;
    a) BRC_AUTHTOKEN=$OPTARG;;
    *) usage && exit 1;;
  esac
done #End arguments
shift $(($OPTIND - 1))

if [ -z $BRC_TENANTID ]; then
  echo "ERROR: Must define BRC_TENANTID in environment or argument"
  usage && exit 1
elif [ -z $BRC_AUTHTOKEN ]; then
  echo "ERROR: Must define BRC_AUTHTOKEN in environment or argument"
  usage && exit 1
fi

ENDPOINT=$IDENTITY_ENDPOINT
DATA=$( curl $ENDPOINT/OS-KSADM/roles \
             -H "Content-Type: application/json" \
             -H "X-Auth-Token: $BRC_AUTHTOKEN" \
          2>/dev/null | brc-json.tool )

IDS=$( echo "$DATA" \
        | sed -n 's/bashrc~roles~id.\([0-9]*\)~.*$/\1/p' )

# Just clean up the output a bit
echo ---
for x in $IDS; do
  echo "$DATA" | grep "\.$x~"
  echo ---
done
