#!/bin/bash

#
# List all users on the given cloud account

function usage() {
  echo "Usage: brc-identity-listusers [-t TENANTID] [-a AUTHTOKEN]"
  echo "Example:"
  echo "  # brc-identity-listusers -t 123456 -a 1a2b3c4d5e6f7g8h9i0j"
  echo "Example:"
  echo "  # export TENANTID=123456"
  echo "  # export AUTHTOKEN=1a2b3c4d5e6f7g8h9i0j"
  echo "  # brc-identity-listusers"
}

while getopts ":ht:a:" arg; do
  case $arg in
    t) TENANTID=$OPTARG;;
    a) AUTHTOKEN=$OPTARG;;
    *) usage && exit 1;;
  esac
done #End arguments
shift $(($OPTIND - 1))

if [ -z $TENANTID ]; then
  echo "ERROR: Must define TENANTID in environment or argument"
  usage && exit 1
elif [ -z $AUTHTOKEN ]; then
  echo "ERROR: Must define AUTHTOKEN in environment or argument"
  usage && exit 1
fi

ENDPOINT=$IDENTITY_ENDPOINT
USERDATA=$( curl $ENDPOINT/users \
                 -H "Content-Type: application/json" \
                 -H "X-Auth-Token: $AUTHTOKEN" \
              2>/dev/null | brc-json.tool )

echo "$USERDATA"
exit 0

AUTHTOKEN=$( echo "$USERDATA" \
              | sed -n 's/^bashrc:access:token:id://p' )
TENANTID=$( echo "$TOKENDATA" \
              | sed -n 's/^bashrc:access:token:tenant:id://p' )
EXPIRES=$( echo "$TOKENDATA" \
              | sed -n 's/^bashrc:access:token:expires://p' )

echo "AUTHTOKEN=$AUTHTOKEN"
echo "TENANTID=$TENANTID"
echo "EXPIRES=$EXPIRES"
