#!/bin/bash

#
# Parses the credential file with Rackspace-specific labels.
if [ $# -ne 1 ]; then
  echo "ERROR: Must provide path to credentials file."
  exit 1
elif [ ! -f $1 ]; then
  echo "ERROR: File does not exist: $1"
  exit 1
fi
source $1

