#!/bin/bash

#
# List all users on the given cloud account

. $BASHRC_BASE/bashrc/errors.bash

function usage() {
  echo "Usage: brc-identity-deleteuser [-h] [-a BRC_AUTHTOKEN] -i USERID"
  echo "Example:"
  echo "  # brc-identity-deleteuser -a 1a2b3c4d5e6f7g8h9i0j \\"
  echo "  #                         -i 477f91eab3a111e3aa12f30ec4c95229"
  echo "Example:"
  echo "  # export BRC_AUTHTOKEN=1a2b3c4d5e6f7g8h9i0j"
  echo "  # brc-identity-deleteuser -i 477f91eab3a111e3aa12f30ec4c95229"
  echo "Arguments:"
  echo "  -a X	API authentication token"
  echo "  -h	Print this help"
  echo "  -i X  ID of user to delete"
}

USAGEFLAG=0
while getopts ":ha:i:" arg; do
  case $arg in
    a) BRC_AUTHTOKEN=$OPTARG;;
    i) USERID=$OPTARG;;
    h) usage && exit 0;;
    :) echo "ERROR: Option -$OPTARG requires an argument."
       USAGEFLAG=1;;
    *) echo "ERROR: Invalid option: -$OPTARG"
       USAGEFLAG=1;;
  esac
done #End arguments
shift $(($OPTIND - 1))

if [ -z "$BRC_AUTHTOKEN" ]; then
  echo "ERROR: Must define BRC_AUTHTOKEN in environment or argument"
  USAGEFLAG=1
fi
if [ -z "$USERID" ]; then
  echo "ERROR: Must define USERID in environment or argument"
  USAGEFLAG=1
fi

if [ $USAGEFLAG -ne 0 ]; then
  usage && exit 1
fi

DATA=$( curl --write-out \\n%{http_code} --silent --output - \
             $IDENTITY_ENDPOINT/users/$USERID \
             -X DELETE \
             -H "Content-Type: application/json" \
             -H "X-Auth-Token: $BRC_AUTHTOKEN" \
          2>/dev/null )
RETVAL=$?
CODE=$( echo "$DATA" | tail -n 1 )

# Check for failed API call
if [ $RETVAL -ne 0 ]; then
  errorcurlfail
elif [[ $(echo "$CODE" | grep -cE '^2..$') -eq 0 ]]; then
  errornot200 $CODE $( echo "$DATA" | head -n -1 )
fi

DATA=$( echo "$DATA" | head -n -1 | brc-json.tool )

# Just clean up the output a bit
echo "User deleted."
