#!/bin/bash

#
# Import an image from local file to Rackspace Cloud

. $BASHRC_BASE/bashrc/errors.bash

function usage() {
  echo "Usage: brc-image-export [-h] [-a BRC_AUTHTOKEN] [-t BRC_TENANTID] \\"
  echo "                        [-r BRC_REGION] -i IMAGEID -c CONTAINER"
  echo "Example:"
  echo "  # brc-image-export -a 1a2b3c4d5e6f7g8h9i0j \\"
  echo "                     -t 123456 \\"
  echo "                     -r dfw \\"
  echo "                     -i bb1e7a7e-caff-11e3-8604-e7e905fb9520 \\"
  echo "                     -c exported-images"
  echo "Arguments:"
  echo "  -a X	Authentication token.  This can be set via the environment"
  echo "        variable BRC_AUTHTOKEN instead of as an argument."
  echo "  -c X  Cloud Files container name to use as export destination."
  echo "  -h	Print this help."
  echo "  -i X  ID of image that will be exported to Cloud Files."
  echo "  -r X  Region.  Examples: iad, dfw, ord, syd.  This can be set via"
  echo "        the environment variable BRC_REGION instead of as an"
  echo "        argument."
  echo "  -t X	Tenant ID (DDI).  This can be set via the environment"
  echo "        variable BRC_TENANTID instead of as an argument."
}

USAGEFLAG=0
while getopts ":ha:t:r:c:i:" arg; do
  case $arg in
    a) BRC_AUTHTOKEN=$OPTARG;;
    r) BRC_REGION=$OPTARG;;
    t) BRC_TENANTID=$OPTARG;;
    c) CONTAINER=$OPTARG;;
    i) IMAGEID=$OPTARG;;
    h) usage && exit 0;;
    :) echo "ERROR: Option -$OPTARG requires an argument."
       USAGEFLAG=1;;
    *) echo "ERROR: Invalid option: -$OPTARG"
       USAGEFLAG=1;;
  esac
done #End arguments
shift $(($OPTIND - 1))

if [ -z "$BRC_AUTHTOKEN" ]; then
  echo "ERROR: Must define BRC_AUTHTOKEN in environment or argument"
  USAGEFLAG=1
fi
if [ -z "$BRC_TENANTID" ]; then
  echo "ERROR: Must define BRC_TENANTID in environment or argument"
  USAGEFLAG=1
fi
if [ -z "$BRC_REGION" ]; then
  echo "ERROR: Must define BRC_REGION in environment or argument"
  USAGEFLAG=1
fi
if [ -z "$CONTAINER" ]; then
  echo "ERROR: Must define CONTAINER as argument"
  USAGEFLAG=1
fi
if [ -z "$IMAGEID" ]; then
  echo "ERROR: Must define IMAGEID as argument"
  USAGEFLAG=1
fi

if [ $USAGEFLAG -ne 0 ]; then
  usage && exit 1
fi

if [ -z "$IMAGENAME" ]; then
  IMAGENAME=$( basename $IMAGEFILE )
fi

BRC_REGION=$( echo $BRC_REGION | tr 'A-Z' 'a-z' )
IMAGE_ENDPOINT=$( $BRCUTIL/brc-util-imageendpoint -r $BRC_REGION )

# Currently only supports VHD format - keep hardcoded
DATA=$( curl --write-out \\n%{http_code} --silent --output - \
             $IMAGE_ENDPOINT/tasks \
             -X POST \
             -H "Content-Type: application/json" \
             -H "Accept: application/json" \
             -H "X-Auth-Token: $BRC_AUTHTOKEN" \
             -H "X-Auth-Project-Id: $TENANTID" \
             -H "X-Tenant-Id: $TENANTID" \
             -H "X-User-Id: $TENANTID" \
             -d '{ "type": "export",
                   "input": {
                     "image_uuid": "'$IMAGEID'",
                     "receiving_swift_container": "'$CONTAINER'" } }' \
          2>/dev/null )
RETVAL=$?
CODE=$( echo "$DATA" | tail -n 1 )

# Check for failed API call
if [ $RETVAL -ne 0 ]; then
  errorcurlfail
elif [[ $(echo "$CODE" | grep -cE '^2..$') -eq 0 ]]; then
  errornot200 $CODE $( echo "$DATA" | head -n -1 )
fi

DATA=$( echo "$DATA" | head -n -1 | $BRCUTIL/brc-util-json.tool )

echo "$DATA"
exit 0
